carpentries/lesson-example

LAYOUT.md

This PR adds instruction on changing the URL linked to the "Source" button in the page footer.  
It originates from [this thread](http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2015-December/003582.html) in the [Discuss] mailing list.

Instructions on changing the URL linked to the "Source" button

---

_includes/header.html
_includes/javascript.html

The current jQuery file location produces a 404, and also a security warning in browsers now that GitHub Pages is using HTTPS by default (eg https://swcarpentry.github.io/python-novice-inflammation/).  In addition, because Bootstrap's JavaScript requires jQuery, a browser console errors currently occur on all pages.  The HTML5 shim will produce a security warning in IE as it is loaded from HTTP rather than HTTPS.
This PR uses Google's hosted jQuery API, which is free and uses HTTPS (plus as a bonus provides a global CDN for speed), and adjusts the HTML5 shim to use HTTPS, resolving all above issues.
The URL needs to be updated out in the Python and Shell lessons, and probably elsewhere, so what's the best way of having this cherry-picked?

Update JavaScript locations to avoid errors

---

README.md

I thought the hyphenated form was current when I used it in 0d8da61e
(README.md: Add local maintainer listing, 2015-04-15, #2), but GitHub
no longer recognizes the hyphenated form.  The un-hyphenated form
seems to [date back to 2012-03-06][1], so maybe I was just confused ;).
Anyhow, fixing to use the current username.
Ping @rgaiacs ;).
[1]: https://github.com/rgaiacs

README: Update 'r-gaia-cs' -> 'rgaiacs'

---

_extras/guide.md

The mentoring subcommittee has requested that we change the name of the "Instructors' Guide" to "Instructor Notes," to avoid confusion with new roles called "guides" being developed, as well as make it easier to reference where instructors can go to find help. This PR only changes the title on the page (and corresponding changes in the content of `_episodes/03-organization.md`). 
It seems simplest to leave filenames as described now (e.g., `guide.md`), but I am interested in finding out if others believe this to be the best, most sustainable solution.

Disambiguating "guides"

---

_extras/guide.md
_includes/syllabus.html
setup.md

Replaces #56:
1. Adds ID attribute to syllabus.
2. Links to that instead of using `page.root`.

Adding link to syllabus (episodes) from setup instructions

---

_episodes/02-tooling.md

The example source block line currently renders as
Today we are going to study .
This change causes it to display as
Today we are going to study {{page.name}}.

Fix display of double curlies using {% raw %}

---

_extras/guide.md

I've tried my hand at a draft of an instructor guide template. I've made the assumption that the guide should be a supplement to the lesson, rather than required reading (e.g, lessons should be stand-alone, for both instructor and learner use). I've tried to make this as generalizable to the whole set of DC/SWC lessons as possible (with the hope that DC adopts the new SWC template, but this certainly isn't required to use the language in this instructor guide template). This structure seems to be relatively easy to adopt into existing instructor guides, and would also help ease the way for new instructor guides to be developed.
This template is relatively simple, but I would be in favor of adding more structure to the section on lesson design and am open to any ideas!

Adding structure to instructor guides/notes

---

CONTRIBUTING.md

Hi,
I added a reference to the _episodes directory where the lesson material is located. As a novice (sort of) to github, it was quite difficult to figure out how to contribute. Hope this helps future contributors.

Add reference to _episodes for lesson contribution

---

README.md

The link worked fine, but directing people to the setup.md file instead of the rendered page means that other links don't work - such as item 12 in the setup page: https://github.com/swcarpentry/lesson-example/blob/gh-pages/setup.md

Change target of setup link from .md to site page

---

_episodes/04-formatting.md

Kramdown will add id for all headers. These headers can be used to linking directly sections of the lesson (also exercises, call outs, etc.). This PR adds a call out explaining this feature.
closes https://github.com/swcarpentry/styles/issues/94

add a callout about header IDs

---

_episodes/04-formatting.md

This will make the links more stables because Jekyll will handle.

Change recommendation for link

---

_config.yml

Per _config.yml in workshop-template, adding Library Carpentry website info for appropriate linking in _includes/lesson_footer.html

Add Library Carpentry website to _config.yml

---

index.md

The link to setup is broken. This pull request suggest to link to the existing setup page (`{{ page.root}}/setup.html`), but other options are 
to change the permalink on Setup to `{{ site.url }}/setup/`

Fix link to setup page in index

---

_episodes/01-design.md

This PR updates information on formative assessments to match current recommendations in the Instructor Training curriculum. 
From the [Importance of Practice](http://carpentries.github.io/instructor-training/02-practice-learning/) episode:
> > Instructors should use a formative assessment ideally every 5 minutes and at least every 10-15 minutes in order to make sure that the class is actually learning. Since the average attention span is usually only this long, formative assessments also help break up instructional time and re-focus attention.
I've also removed the reference to Parson's problems here, as they are no longer taught in Instructor Training.

update info on formative assessments

---

_episodes/03-organization.md

Many episodes (both DC and SWC) are much longer than 20 minutes. For example:
Most [DC Ecology Python](http://www.datacarpentry.org/python-ecology-lesson/) episodes.
Most [DC Genomics Wrangling](http://www.datacarpentry.org/wrangling-genomics/) episodes.
Most [SWC Python Inflammation](http://swcarpentry.github.io/python-novice-inflammation/) episodes (if time was added for exercises, currently all exercises are set at 0 minutes).
Several [SWC R Gapminder](http://swcarpentry.github.io/r-novice-gapminder/) episodes.
Etc.
Previously, we had restricted episode length to ~15-20 minutes and had exercises between episodes to introduce appropriate breaks in lecturing. Now we intersperse exercises during the episode to introduce breaks. Thus episodes no longer need to be keep below 20 minutes.

remove episode length

---

_episodes/08-maintenance.md

We are working to update our Maintainer onboarding process. Part of this new process will involve reading through the Lesson Example. This PR makes modifications to the Lesson Example to reflect changes to the Maintainer onboarding process.
- Changes "one or two" to "multiple" as most repos will now have 3+ Maintainers.
- Remove sentence about deciding on changes to lesson template, as that is now the job of the Lesson Infrastructure committee.
- Updates names of Carpentry Steering Committee post-merger.
- Adds new process for Maintainer onboarding with relevant links.
- Adds capitalization for Maintainer as a specific role in the community.

update maintenance process

---

_episodes/07-checking.md

The link to setup page was going to a 404. I've updated it to point specifically at the part of the setup instructions that talk about installing jekyll and it's dependencies.

fix link to setup instructions

---

setup.md

If you have an out dated Ruby version it may fail to work with jekyll.

Ensure  Ruby is updated to work with Jekyll on OSX

---

_episodes/04-formatting.md

The 'input' (raw) block showed the `.source` class identifier, but the rendered output used `.language-python`.

Fix class mismatch in formatting lesson

---

setup.md

Adding an R package is not obvious if learners have installed Anaconda. Not sure where this lesson might fall in the grand scheme of things, but adding the simple command-line example helps.

Adding How to add R packages

---

CONDUCT.md
LICENSE.md
_config.yml
_extras/about.md
_extras/discuss.md
_extras/figures.md
_extras/guide.md
aio.md
index.md
setup.md

Because we can use `_config.yml`.
Related with swcarpentry/lesson-example#205

Remove root and page from YAML header

---

_episodes/01-design.md
_includes/syllabus.html

The lesson example page (http://carpentries.github.io/lesson-example/) included a section on Lesson Design.  This is deprecated in favor of the new Curriculum Development Handbook (https://carpentries.github.io/curriculum-development/).
This PR hides the Lesson Design from the Lesson Example site, while keeping the placeholder link to allow it to redirect to the new CDH.  The CDH is also linked to in the top paragraph of the lesson Example page.

hides old lesson guide

---

.travis.yml
_episodes/04-formatting.md
bin/boilerplate/.travis.yml
bin/generate_md_episodes.R
bin/lesson_check.py
bin/repo_check.py

It's possible to add spellchecking to your travis configuration with something like
```
jobs:
include:
- stage: spelling
before_install:
install:
pip install codespell
script: codespell --skip="assets,fig,*.svg,AUTHORS,.mailmap" --quiet-level=2 --ignore-words-list="rouge"
```
This PR does that and corrects the typos that `codespell` found.

Add spellchecking to travis

---

_includes/sc/syllabus.html

Unless I miss something, I don't see Python Gapminder lesson in the SWC
syllabus... So, I'm adding it here.

SWC Syllabus: add Python Gapminder lesson

---

_includes/sc/syllabus.html

OpenRefine is not part of the Software Carpentry but of the Library
Carpentry. Just cleaning up.
---

SWC Syllabus: remove OpenRefine

---

_includes/sc/syllabus.html

Fixing inaccurate names of some SWC lessons in the Syllabus.

SWC Syllabus: fix lesson names

---

setup.md

Link currently goes to nowhere, new link goes to Episode 3 of this lesson which seems more relevant for what is described.

Fixes broken link in part 14 of setup.md

---

_episodes_rmd/05-rmarkdown-example.Rmd

Improve code block that specifies what lesson developers have to
add to their Rmd-based episodes.

05-rmarkdown-example.Rmd: fix instructions for R-markdown files

---

setup.md

Following https://github.com/carpentries/maintainer-RFCs/issues/1, here is a first draft of the updated setup instructions for Maintainers and community members to be able to render the lessons locally using Bundler. 
These are far from being done and we'd love feedback from Maintainers to make them better and accurate.
1. The Windows installation instructions need to be better tested, especially by people who are not set up yet and need to go through the instructions and by people with more technical knowledge about Windows than I do to double-check that the instructions are comprehensive and accurate.
2. The macOS installation instructions need to be fully written. Unfortunately, I don't have this system at my disposal which makes writing installation instructions challenging.
3. Any …

add bundler installation and comprehensive setup instructions

---

_episodes/03-organization.md

I think this reflects the current recommendations, to make the lesson suitable for local building as well as online delivery?

remove instructions to set layout and permalink in individual files

---

_episodes/03-organization.md

adds a new section in `03-organization`, describing the use of `episode_order` and `extras_order`.

document manual ordering of episodes and extras

---

_episodes/04-formatting.md

`{: .html}` -> `{: .language-html}`

correct class for HTML syntax highlighting

---

_episodes/04-formatting.md

- Italicize i.e.
- Changed "Jekyll's tag link" to "Jekyll's link tag" because we're talking about a tag, not a link
- Changed https://jekyllrb.com/docs/templates/#links (which no longer works) to https://jekyllrb.com/docs/liquid/tags/#link

04-formatting.md: update Jekyll's link tag link, update formatting

---

_episodes/04-formatting.md

As the number of lessons in The Carpentries Incubator increases, there is a growing need to provide code examples beyond the core languages traditionally taught in The Carpentries. Rouge and kramdown allow for syntax highlighting of most languages, but the lesson template isn't fully compatible with languages other than Bash, HTML, Make, MATLAB, Python, R, and SQL. Nevertheless, I think it is important that the lesson developers can read in the Lesson Example about how to activate highlighting of other languages. 
This PR adds an expandable box providing information about how to activate syntax highlighting for blocks of code in languages other than those listed above.

Document syntax highlighting for non-core languages

---

_episodes/02-tooling.md

Users often run into trouble when forgetting to leave a blank line between the closing `---` of the page front matter and the beginning of the page content. To reduce confusion, this PR updates the example code block to include a blank line.

include a blank line between example header and content

---

.github/workflows/template.yml
.github/workflows/website.yml
CODE_OF_CONDUCT.md
Gemfile
Makefile
_includes/links.md
assets/css/lesson.scss
bin/dependencies.R
bin/lesson_check.py
bin/markdown_ast.rb
bin/util.py
bin/workshop_check.py

This update reorganizes the makefile a bit, adds an image-with-shadow class, updates link colours, updates links, and updates a lot of corner cases.
I updated the styles via the flight rules: https://github.com/carpentries/maintainer-resources/blob/main/FLIGHT_RULES.md#update-styles

Update styles 2021-04-14

---

setup.md

I noticed that the enumerated list under "macOS" on the Setup page restarts with the "1. Ruby..." instruction, even though it is a continuation of instructions. I fixed the markdown so that everything aligns and the enumeration is contiguous.

Fixed Indentation and Enumeration in MacOS Setup Instructions

---

_episodes/04-formatting.md

The sentence _Each special blockquote must started with a level-2 header_ is grammatically incorrect.
I propose using _Each special blockquote must begin with a level-2 header_ instead.
Other possibilities are:
- _Each special blockquote must be started with a level-2 header_.
- _Each special blockquote must start with a level-2 header_.

Typo: missing verb

---

setup.md

On my Windows computer, the `C:\Ruby26-x64\bin` directory contains the primary `ruby.exe` and batch files for running bundler. This was the ONLY environment variable path for Ruby and rendering worked.  For using `make`, the `C:\Ruby26-x64\msys64\mingw64\bin` directory contains `mingw32-make.exe`. I believe the environment variables should include both paths. 
Also, after clicking on "Advanced system settings", one has to choose to edit either "User variables for <localuser>" or "System variables". Both sections have `path` entries. Editing the local user path is identical to the system variables.
<details>
<summary><strong>Instructions</strong></summary>
Thanks for contributing! :heart:
If this contribution is for instructor training, please email the link to this contribution to …

Add an environment variable to include `bundler`

---

_episodes/04-formatting.md

Adding a section to `04-formatting` that shows how to add math support for an episode.

Document mathematical expression support
