carpentries/lesson-example

LAYOUT.md

README needs to be created from scratch.

---

_includes/syllabus.html

@gvwilson This is proposed based on the discussion about the python-novice-inflammation lesson.

Adding a footnote to the schedule that it may vary.

---

_extras/guide.md
setup.md

Mention that R packages are needed to build example lesson.

---

README.md
setup.md

These should also work on the built site, if I understand things correctly.

Update a few files to make this directly readable on github

---

_episodes/06-rmarkdown-example.md
_episodes_rmd/06-rmarkdown-example.Rmd

add more information about pkgs needed to build the lesson

---

index.md

I was having trouble adding block styling until I figured out that style tags need to be on a newline.

Style tags need to go on a newline

---

_episodes/03-organization.md

Add information about where to store figures

---

_episodes/04-formatting.md

Document Maximum Line Length

---

README.md

Please delete the text below before submitting your contribution. 
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck …

fixed broken link on landing page

---

setup.md

Add note about version of Jekyll needed per https://github.com/swcarpentry/styles/issues/195#issuecomment-351056899.

jekyll version

---

_episodes/02-tooling.md

indent HTML

---

_episodes/06-style-guide.md

support screen readers

---

_episodes/08-maintenance.md
_includes/links.md

Specify release repo unambiguously

---

bin/lesson_initialize.py

This intends to fix issue #182 
Please review and merge if acceptable
---

Intends to fix issue 182

---

CONTRIBUTING.md
_episodes/04-formatting.md
_episodes/05-rmarkdown-example.md
_extras/about.md
_extras/discuss.md
_extras/guide.md
_includes/links.md

I had to rebase #186 to keep the commits when moving some to styles.

Rebase of (#186) Assorted minor fixes to spelling, whitespace, hyperlinks & sorting

---

_episodes/06-style-guide.md

fix typo (minor grammatical error)

fix typo in explanation of keystroke explanationn

---

setup.md

Fix typo on jekyll install

---

setup.md

As remarked by @maxim-belkin, see *[PR that was closed too early](https://github.com/carpentries/lesson-example/pull/212#issuecomment-396661687)*  ;-)

Fix typo as identified by @maxim-belkin

---

_episodes/07-checking.md
_includes/links.md

Related with carpentries/lesson-example#222.

Remove section Displaying Figures

---

CONTRIBUTING.md
_episodes/03-organization.md
bin/boilerplate/CONTRIBUTING.md
setup.md

Same as https://github.com/carpentries/styles/pull/350 ;-)

Reflect Apple's rebranding

---

_episodes/04-formatting.md

replace sub-heading with sub-title

---

_episodes/06-style-guide.md

Added a bunch of code blocks declarations.

06-style-guide.md: declare code block types

---

_episodes/01-design.md

This is an attempt to improve wording and visual representation of material in the first episode.
No significant changes.

01-design.md: improve wording

---

_episodes/06-style-guide.md

Relates to https://github.com/carpentries/workshop-template/pull/595

Add note about title casing to style guide

---

setup.md

Improve Jekyll setup instructions

---

setup.md

Fixes broken link in setup.md

---

_config.yml

To help users of the lesson template understand how to choose/when to update the value of life_cycle

link to Lesson Life Cycle chapter of CDH

---

_episodes/02-tooling.md
index.md
setup.md

Add instructions for manual import

---

_episodes/03-organization.md

To help Incubator developers with the setup of their lesson repositories.

mention "cp" and "incubator" options for "carpentry"

---

_episodes_rmd/05-rmarkdown-example.Rmd

I forgot to apply the changes to #318! 
See https://github.com/carpentries/lesson-example/pull/318#issuecomment-771919555 for my failure.

Fix documentation for branch names and automation.

---

README.md

Set appropriate test badges in README add the `website` workflow badge.

ENH: Set appropriate test badges in README

---

README.md

Fix `website` workflow badge in README.

DOC: Fix `website` workflow badge in README

---

_episodes_rmd/05-rmarkdown-example.Rmd

adjusting the source Rmd in line with @vinisalazar's fix in #330

split long line text across multiple lines

---

_episodes/04-formatting.md

Documenting the changes made in https://github.com/carpentries/styles/pull/514

document image-with-shadow class

---

setup.md

adding select System variables section

Specifying the System variables

---

.github/workflows/update-styles.yml

prevent weekly workflow from running on forks

---

_episodes/07-checking.md

This will address https://github.com/swcarpentry/git-novice/issues/850#issuecomment-971773833

add callout to address local/live divide

---

setup.md

Alt text contributed by Alycia Crall, https://carpentries.github.io/lesson-example//fig/using-github-import.png

update alt text

---

_episodes/04-formatting.md

Adding `.caution` to the list of special block quotes

---

README.md
bin/boilerplate/README.md

Update slack links to point to the new domain URL and invite app.

Update slack links
